# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelTable(
            name='foo',
            table='xxx',
        ),
        migrations.AlterModelTable(
            name='foo2',
            table='yyy',
        ),
    ]
